import SearchableSelect from '../components/SearchableSelect';
import { useState } from 'react';
import { getCurrentUser } from '../lib/auth';
import { formValues,isTeacher,mutate,useResource,type Catalog } from '../lib/community';
import { ActionStatus,CommunityPage,Empty,ErrorBox,Field,Submit,useAction } from '../components/CommunityUI';
export default function CourseCatalog() {
  const result=useResource<Catalog>('/catalog'),action=useAction();
  const [university,setUniversity]=useState('uos'),[major,setMajor]=useState(''),[shared,setShared]=useState(false);
  if(!isTeacher(getCurrentUser()?.role))return <CommunityPage title="Course Catalogue"><Empty>Only tutors and study group leaders can add courses.</Empty></CommunityPage>;
  return <CommunityPage title="Add a Course"><ErrorBox error={result.error}/><ActionStatus action={action}/><form className="editor-form" onSubmit={e=>{e.preventDefault();const form=e.currentTarget;const body={...formValues(form),isShared:shared};void action.run(async()=>{await mutate('/catalog/entries',body);result.reload();},'Course added to the university catalogue.');}}><div className="form-grid"><Field label="University"><SearchableSelect name="universityId" value={university} onChange={e=>{setUniversity(e.target.value);setMajor('');}}><option value="">Add another university</option>{result.data?.universities.map(u=><option key={u.id} value={u.id}>{u.name}</option>)}</SearchableSelect></Field>{!university&&<><Field label="University name"><input name="universityName" required minLength={3} maxLength={200}/></Field><Field label="Official university website"><input name="website" type="url" required placeholder="https://www.example.ac.ae"/></Field></>}{!shared&&<><Field label="Major"><SearchableSelect name="majorId" value={major} onChange={e=>setMajor(e.target.value)}><option value="">Add a major</option>{result.data?.majors.filter(m=>m.universityId===university).map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</SearchableSelect></Field>{!major&&<Field label="Major name"><input name="majorName" required minLength={2} maxLength={200}/></Field>}</>}<Field label="Course code"><input name="code" required maxLength={30}/></Field><Field label="Course name"><input name="name" required minLength={2} maxLength={240}/></Field><Field label="Official curriculum / course URL"><input name="sourceUrl" type="url" required placeholder="https://..."/></Field></div><label className="checkbox-label"><input type="checkbox" checked={shared} onChange={e=>setShared(e.target.checked)}/>Shared university course / elective</label><Submit busy={action.busy}>Add course</Submit></form></CommunityPage>;
}
