import { useState } from 'react';
import { AdminDashboard } from './Reports';
import { Link } from 'react-router-dom';
import { Check,X,Trash2,Plus,Calendar } from 'lucide-react';
import { useCurrentUser } from '../lib/auth';
import { dateTime,formValues,isTeacher,mutate,timedValues,useResource,type Booking,type DashboardData } from '../lib/community';
import { ActionStatus,CatalogSelect,CommunityPage,Empty,ErrorBox,External,Field,Submit,useAction } from '../components/CommunityUI';

function BookingRow({booking:b,onChange}:{booking:Booking;onChange:()=>void}) {
  const action=useAction(),user=useCurrentUser(),isTutor=b.tutorId===user?.id;
  const active=['pending','accepted'].includes(b.status)&&new Date(b.startsAt)>new Date();
  return <article className="booking-row"><div className="section-heading"><h3>{isTutor?b.student:b.tutor}</h3><span className={'status-badge '+b.status}>{b.status}</span></div><p>{dateTime(b.startsAt)} - {dateTime(b.endsAt)}</p><p><strong>AED {Number(b.price).toFixed(2)} total</strong></p>{!isTutor&&b.status==='accepted'&&Number(b.price)>0&&b.paymentStatus!=='paid'&&active&&<Link className="text-link" to={'/checkout?kind=booking&reference='+b.id}>Pay for session</Link>}{b.paymentStatus&&<p className="muted">Test payment: {b.paymentStatus}</p>}{b.note&&<p className="preserve-lines muted">{b.note}</p>}{b.status==='accepted'&&b.meetingUrl&&<External href={b.meetingUrl}>Open meeting</External>}{active&&<div>{isTutor&&b.status==='pending'&&<form className="accept-form" onSubmit={e=>{e.preventDefault();const meetingUrl=new FormData(e.currentTarget).get('meetingUrl');void action.run(async()=>{await mutate('/tutors/bookings/'+b.id,{status:'accepted',meetingUrl},'PATCH');onChange();},'Booking accepted; student notified.');}}><Field label="Teams / meeting link"><input name="meetingUrl" type="url" required placeholder="https://teams.microsoft.com/..."/></Field><button className="action-button" disabled={action.busy}><Check size={16}/>Accept</button></form>}<div className="flex gap-3 mt-3">{isTutor&&b.status==='pending'&&<button className="secondary-button" disabled={action.busy} onClick={()=>void action.run(async()=>{await mutate('/tutors/bookings/'+b.id,{status:'declined'},'PATCH');onChange();},'Booking declined; student notified.')}><X size={16}/>Decline</button>}<button className="secondary-button" disabled={action.busy} onClick={()=>{if(window.confirm('Cancel this booking?'))void action.run(async()=>{await mutate('/tutors/bookings/'+b.id,{status:'cancelled'},'PATCH');onChange();},'Booking cancelled.');}}>Cancel booking</button></div></div>}<ActionStatus action={action}/></article>;
}
export default function Dashboard() {
  const user=useCurrentUser(),result=useResource<DashboardData>('/account/dashboard',15000),action=useAction();
  const tutor=user?.role==='tutor';
  const [view,setView]=useState('sessions');
  if(user?.role==='admin')return <AdminDashboard/>;
  return <CommunityPage showTabs={false} title={tutor?'Tutor Dashboard':user?.role==='leader'?'Study Group Leader Dashboard':'My Learning'} action={isTeacher(user?.role)&&<Link className="text-link" to="/catalog">Add university / course</Link>}><ErrorBox error={result.error}/><ActionStatus action={action}/>{result.loading?<Empty>Loading your dashboard...</Empty>:result.data&&<>
    {tutor&&<div className="flex flex-wrap gap-3 mb-6"><button className="secondary-button" aria-pressed={view==='sessions'} onClick={()=>setView('sessions')}>Requests and sessions</button><button className="secondary-button" aria-pressed={view==='availability'} onClick={()=>setView('availability')}>Profile and availability</button></div>}
    {tutor&&view==='availability'&&<section className="detail-section"><h2>Tutor profile and availability</h2><div className="dashboard-columns"><form className="editor-form" onSubmit={e=>{e.preventDefault();const body=formValues(e.currentTarget);void action.run(async()=>{await mutate('/tutors/profile',body,'PUT');result.reload();},'Tutor profile saved.');}}><h3>Public profile</h3><CatalogSelect initialUniversity={result.data.profile?.universityId}/><Field label="Subjects / course codes"><input name="subjects" required minLength={3} maxLength={500} defaultValue={result.data.profile?.subjects}/></Field><Field label="About your tutoring"><textarea name="bio" required minLength={20} maxLength={5000} rows={4} defaultValue={result.data.profile?.bio}/></Field><Field label="Hourly rate (AED)"><input name="hourlyRate" type="number" min="0" max="10000" step="0.01" required defaultValue={result.data.profile?.hourlyRate}/></Field><Submit busy={action.busy}>Save profile</Submit></form>
      <div>{result.data.profile?<><form className="editor-form" onSubmit={e=>{e.preventDefault();const body=timedValues(e.currentTarget);void action.run(async()=>{await mutate('/tutors/slots',body);result.reload();},'Availability added.');}}><h3>New availability</h3><Field label="Starts (your local time)"><input name="startsAt" type="datetime-local" required/></Field><Field label="Ends (your local time)"><input name="endsAt" type="datetime-local" required/></Field><Field label="Total price for this session (AED)"><input name="price" type="number" min="0" max="10000" step="0.01" required defaultValue={result.data.profile.hourlyRate}/></Field><Submit busy={action.busy}>Add slot</Submit></form><Link className="text-link" to={'/tutors/'+user?.id}>View public profile</Link></>:<Empty>Save your tutor profile to publish availability.</Empty>}{result.data.slots.filter(s=>!s.cancelled).map(s=><div className="detail-row" key={s.id}><div><strong>{dateTime(s.startsAt)}</strong><p className="muted">AED {Number(s.price).toFixed(2)} · {s.reserved?'Requested / booked':'Open'}</p></div><button className="icon-button" title="Cancel slot" disabled={action.busy} onClick={()=>{if(window.confirm('Cancel this slot? Any booked student will be notified.'))void action.run(async()=>{await mutate('/tutors/slots/'+s.id,undefined,'DELETE');result.reload();},'Slot cancelled.');}}><Trash2 size={18}/></button></div>)}</div></div></section>}
    {(!tutor||view==='sessions')&&<section className="detail-section"><h2>{tutor?'Booking Requests and Sessions':'My Bookings'}</h2>{!result.data.bookings.length?<Empty>No bookings yet. <Link className="text-link" to="/tutors">Find a tutor</Link></Empty>:<div className="booking-list">{result.data.bookings.map(b=><BookingRow key={b.id} booking={b} onChange={result.reload}/>)}</div>}</section>}
    <section className="detail-section"><div className="section-heading"><h2>My Study Groups</h2><Link className="text-link" to="/study-groups">Browse / create group</Link></div>{!result.data.groups.length?<Empty>You have not joined any groups yet.</Empty>:result.data.groups.map(g=><div className="detail-row" key={g.id}><div><h3><Link to={'/study-groups/'+g.id}>{g.title}</Link></h3><p className="muted">{g.course} · {g.university}</p></div><Link className="text-link" to={'/study-groups/'+g.id}>{g.ownerId===user?.id?'Manage group':'Open group'}</Link></div>)}</section>
    {isTeacher(user?.role)&&<section className="detail-section"><div className="section-heading"><h2>My Campus Events</h2><Link className="text-link" to="/events?create=1"><Plus size={16}/>Publish event</Link></div>{!result.data.events.length?<Empty>No events published yet.</Empty>:result.data.events.map(e=><div className="detail-row" key={e.id}><div><h3><Link to={'/events/'+e.id}>{e.title}</Link></h3><p className="muted">{dateTime(e.startsAt)} {e.cancelled?' · Cancelled':''}</p></div><Link className="text-link" to={'/events/'+e.id}>Edit details</Link></div>)}</section>}
  </>}</CommunityPage>;
}
