import { useState } from 'react';
import { Link,useNavigate,useParams,useSearchParams } from 'react-router-dom';
import { Plus,MapPin,Calendar,Pencil } from 'lucide-react';
import { getCurrentUser } from '../lib/auth';
import { dateTime,eventImage,isTeacher,localInput,mutate,timedValues,useResource,type CampusEvent,type PageData } from '../lib/community';
import { ActionStatus,CatalogSelect,CommunityPage,Empty,ErrorBox,External,Field,Pagination,SearchFilters,Submit,useAction } from '../components/CommunityUI';

export function EventCard({event:e}:{event:CampusEvent}) {return <article className="community-card event-card"><img src={eventImage(e.imageKey)} alt={e.imageKey==='campus'?'University campus':'Event venue'} loading="lazy"/><div><p className="eyebrow">{e.university}</p><h2><Link to={'/events/'+e.id}>{e.title}</Link></h2><p>{dateTime(e.startsAt)}</p><p className="muted">{e.location}</p>{!!e.cancelled&&<span className="status-badge">Cancelled</span>}<Link className="text-link" to={'/events/'+e.id}>Event details</Link></div></article>;}
function EventForm({event,onSaved}:{event?:CampusEvent;onSaved:(id:string)=>void}) {
  const action=useAction();
  return <form className="editor-form" onSubmit={e=>{e.preventDefault();const body=timedValues(e.currentTarget);void action.run(async()=>{const result=await mutate<{id:string}>(event?'/events/'+event.id:'/events',body,event?'PATCH':'POST');onSaved(event?.id||result.id);});}}><h2>{event?'Edit event':'Publish campus event'}</h2><div className="form-grid"><CatalogSelect initialUniversity={event?.universityId}/><Field label="Event title"><input name="title" defaultValue={event?.title} required maxLength={160}/></Field><Field label="Venue / building / room"><input name="location" defaultValue={event?.location} required minLength={3} maxLength={300}/></Field><Field label="Starts (your local time)"><input name="startsAt" type="datetime-local" defaultValue={event?localInput(event.startsAt):''} required/></Field><Field label="Ends (your local time)"><input name="endsAt" type="datetime-local" defaultValue={event?localInput(event.endsAt):''} required/></Field><Field label="Official event page (optional)"><input name="sourceUrl" type="url" defaultValue={event?.sourceUrl||''} placeholder="https://..."/></Field><Field label="Event image"><select name="imageKey" defaultValue={event?.imageKey||'campus'}><option value="campus">Campus</option><option value="global-day">Global Day</option><option value="career-day">Career Day</option><option value="dental-symposium">Dental Symposium</option></select></Field></div><Field label="Event details and attendance information"><textarea name="description" required minLength={20} maxLength={5000} rows={4} defaultValue={event?.description}/></Field><Submit busy={action.busy}>Save event</Submit><ActionStatus action={action}/></form>;
}
export default function Events() {
  const [params]=useSearchParams(),navigate=useNavigate(),user=getCurrentUser();
  const result=useResource<PageData<CampusEvent>>('/events?'+params.toString());
  const [create,setCreate]=useState(params.get('create')==='1');
  return <CommunityPage title="Campus Events" action={isTeacher(user?.role)&&<button className="action-button" onClick={()=>setCreate(!create)}><Plus size={17}/>{create?'Close form':'Publish event'}</button>}>{create&&isTeacher(user?.role)&&<EventForm onSaved={id=>navigate('/events/'+id)}/>}<SearchFilters events/><ErrorBox error={result.error}/>{result.loading?<Empty>Loading events...</Empty>:result.data?.items.length?<div className="community-grid">{result.data.items.map(e=><EventCard key={e.id} event={e}/>)}</div>:!result.error&&<Empty>No events match these filters yet.</Empty>}{result.data&&<Pagination {...result.data}/>}</CommunityPage>;
}
export function EventDetail() {
  const {id}=useParams(),result=useResource<CampusEvent>('/events/'+id),user=getCurrentUser(),action=useAction();
  const [editing,setEditing]=useState(false);
  if(result.loading)return <CommunityPage title="Campus Event"><Empty>Loading event...</Empty></CommunityPage>;
  if(!result.data)return <CommunityPage title="Campus Event"><ErrorBox error={result.error}/></CommunityPage>;
  const e=result.data,owner=e.ownerId===user?.id;
  return <CommunityPage title={e.title} action={owner&&<button className="secondary-button" onClick={()=>setEditing(!editing)}><Pencil size={16}/>Edit event</button>}><ActionStatus action={action}/>{editing&&owner?<EventForm event={e} onSaved={()=>{setEditing(false);result.reload();}}/>:<div className="event-detail"><img src={eventImage(e.imageKey)} alt="Event venue"/><div><p className="eyebrow">{e.university}</p>{!!e.cancelled&&<p className="error-box">This event has been cancelled.</p>}<p className="flex gap-2 items-start"><Calendar size={20}/><span>{dateTime(e.startsAt)}<br/>Ends {dateTime(e.endsAt)}</span></p><p className="flex gap-2 items-start"><MapPin size={20}/>{e.location}</p><p className="preserve-lines">{e.description}</p>{e.sourceUrl&&<External href={e.sourceUrl}>Official event page</External>}{owner&&<button className="secondary-button" disabled={action.busy} onClick={()=>{if(window.confirm(e.cancelled?'Restore this event?':'Mark this event as cancelled?'))void action.run(async()=>{await mutate('/events/'+e.id,{cancelled:!e.cancelled},'PATCH');result.reload();},'Event updated.');}}>{e.cancelled?'Restore event':'Cancel event'}</button>}</div></div>}</CommunityPage>;
}
