import { useEffect,useRef,useState } from 'react';
import { Link,useParams } from 'react-router-dom';
import { Send,Plus,Trash2,Pencil,Video,Users } from 'lucide-react';
import { getCurrentUser } from '../lib/auth';
import { request } from '../lib/api';
import GroupModeration from '../components/GroupModeration';
import { dateTime,formValues,localInput,mutate,timedValues,useResource,type Group,type GroupSession,type Message,type Room } from '../lib/community';
import { ActionStatus,CommunityPage,Empty,ErrorBox,External,Field,Submit,useAction } from '../components/CommunityUI';

function GroupChat({id}:{id:string}) {
  const [messages,setMessages]=useState<Message[]>([]),[error,setError]=useState(''),[older,setOlder]=useState(false),[loading,setLoading]=useState(true),[body,setBody]=useState('');
  const latest=useRef(0),tail=useRef<HTMLDivElement>(null),action=useAction(),user=getCurrentUser();
  const append=(items:Message[])=>{setMessages(current=>[...new Map([...current,...items].map(m=>[m.id,m])).values()].sort((a,b)=>a.id-b.id));if(items.length)latest.current=Math.max(latest.current,...items.map(m=>Number(m.id)));};
  useEffect(()=>{
    let active=true,running=false;latest.current=0;setMessages([]);
    const load=async()=>{if(running)return;running=true;try{const initial=latest.current===0;const result=await request<{messages:Message[];hasMore:boolean}>(`/groups/${id}/messages${initial?'':'?after='+latest.current}`);if(active){append(result.messages);if(initial)setOlder(result.hasMore);setError('');}}catch(e){if(active)setError(e instanceof Error?e.message:'Unable to load chat.');}finally{running=false;if(active)setLoading(false);}};
    void load();const timer=setInterval(load,4000);return()=>{active=false;clearInterval(timer);};
  },[id]);
  return <section className="group-chat"><h2>Group chat</h2><ErrorBox error={error}/>{older&&<button className="text-link" disabled={action.busy} onClick={()=>void action.run(async()=>{const result=await request<{messages:Message[];hasMore:boolean}>(`/groups/${id}/messages?before=${messages[0].id}`);append(result.messages);setOlder(result.hasMore);},'')}>Load earlier messages</button>}<div className="message-list" aria-label="Group messages">{loading?<Empty>Loading messages...</Empty>:!messages.length&&<Empty>No messages yet.</Empty>}{messages.map(m=><article key={m.id} className={'message '+(m.userId===user?.id?'own-message':'')}><header><strong>{m.author}</strong><time>{dateTime(m.createdAt)}</time></header><p>{m.body}</p></article>)}<div ref={tail}/></div><form className="chat-compose" onSubmit={e=>{e.preventDefault();void action.run(async()=>{await mutate(`/groups/${id}/messages`,{body});setBody('');const result=await request<{messages:Message[]}>(`/groups/${id}/messages?after=${latest.current}`);append(result.messages);setTimeout(()=>tail.current?.scrollIntoView({block:'nearest'}),30);},'');}}><textarea aria-label="Message" placeholder="Message the group" value={body} onChange={e=>setBody(e.target.value)} required maxLength={2000} rows={2}/><button className="action-button" disabled={action.busy||!body.trim()} aria-label="Send message" title="Send message"><Send size={19}/></button></form><ActionStatus action={action}/></section>;
}
export default function GroupDetail() {
  const {id}=useParams(),user=getCurrentUser(),action=useAction();
  const group=useResource<Group>('/groups/'+id,30000),room=useResource<Room>(user?`/groups/${id}/room`:null,15000);
  const [sessionForm,setSessionForm]=useState(false),[recordingForm,setRecordingForm]=useState(false),[editing,setEditing]=useState<GroupSession|null>(null),[editGroup,setEditGroup]=useState(false);
  const owner=group.data?.ownerId===user?.id;
  const joined=!!room.data&&!room.error;
  if(group.loading)return <CommunityPage title="Study Group"><Empty>Loading group...</Empty></CommunityPage>;
  if(!group.data)return <CommunityPage title="Study Group"><ErrorBox error={group.error}/></CommunityPage>;
  const g=group.data;
  return <CommunityPage title={g.title} action={owner?<button className="secondary-button" onClick={()=>setEditGroup(!editGroup)}><Pencil size={16}/>Edit group</button>:joined?<button className="secondary-button" disabled={action.busy} onClick={()=>{if(window.confirm('Leave this study group?'))void action.run(async()=>{await mutate(`/groups/${id}/join`,undefined,'DELETE');room.reload();group.reload();},'You left the group.');}}>Leave group</button>:user?<button className="action-button" disabled={action.busy} onClick={()=>void action.run(async()=>{await mutate(`/groups/${id}/join`);room.reload();group.reload();},'You joined the group.')}>Join group</button>:<Link className="action-button" to="/">Sign in to join</Link>}>
    <ActionStatus action={action}/><div className="detail-intro"><p className="eyebrow">{g.code} · {g.course}</p><p className="preserve-lines">{g.description}</p><p className="muted">Led by {g.leader} · {g.university} · {g.members} members</p></div>
    {editGroup&&<form className="editor-form" onSubmit={e=>{e.preventDefault();const body=formValues(e.currentTarget);void action.run(async()=>{await mutate('/groups/'+id,body,'PATCH');setEditGroup(false);group.reload();});}}><Field label="Group name"><input name="title" defaultValue={g.title} required minLength={3} maxLength={160}/></Field><Field label="Description"><textarea name="description" defaultValue={g.description} required minLength={20} maxLength={5000}/></Field><Submit busy={action.busy}>Save group</Submit></form>}
    {room.loading?<Empty>Loading membership...</Empty>:!joined?<div className="empty-state"><Users size={26} className="mx-auto mb-3"/><p>{room.error?.includes('Join this group')||!user?'Sessions, meeting links, recordings and chat are available to group members.':room.error||'Join this group to see its sessions.'}</p></div>:<div className="group-layout"><div><section className="detail-section"><div className="section-heading"><h2>Sessions</h2>{owner&&<button className="secondary-button" onClick={()=>{setEditing(null);setSessionForm(!sessionForm);}}><Plus size={16}/>Add session</button>}</div>
      {owner&&sessionForm&&<form key={editing?.id||'new'} className="editor-form" onSubmit={e=>{e.preventDefault();const body=timedValues(e.currentTarget);void action.run(async()=>{await mutate(`/groups/${id}/sessions${editing?'/'+editing.id:''}`,body,editing?'PATCH':'POST');room.reload();setSessionForm(false);setEditing(null);},editing?'Session updated; members notified.':'Session added; members notified.');}}><Field label="Session title"><input name="title" required maxLength={160} defaultValue={editing?.title}/></Field><Field label="Starts (your local time)"><input name="startsAt" type="datetime-local" required defaultValue={editing?localInput(editing.startsAt):''}/></Field><Field label="Ends (your local time)"><input name="endsAt" type="datetime-local" required defaultValue={editing?localInput(editing.endsAt):''}/></Field><Field label="Teams / meeting link"><input name="meetingUrl" type="url" required placeholder="https://teams.microsoft.com/..." defaultValue={editing?.meetingUrl}/></Field><Submit busy={action.busy}>Save session</Submit></form>}
      {!room.data.sessions.length&&<Empty>No sessions scheduled yet.</Empty>}{room.data.sessions.map(s=><article className="detail-row" key={s.id}><div><h3>{s.title}</h3><p className="muted">{dateTime(s.startsAt)}<br/>Ends {dateTime(s.endsAt)}</p>{s.cancelled?<span className="status-badge">Cancelled</span>:new Date(s.endsAt)<new Date()?<span className="status-badge">Finished</span>:<External href={s.meetingUrl}>Open meeting</External>}</div>{owner&&!s.cancelled&&<div className="flex gap-1"><button className="icon-button" title="Edit session" onClick={()=>{setEditing(s);setSessionForm(true);}}><Pencil size={17}/></button><button className="icon-button" title="Cancel session" disabled={action.busy} onClick={()=>{if(window.confirm('Cancel this session and notify members?'))void action.run(async()=>{await mutate(`/groups/${id}/sessions/${s.id}`,undefined,'DELETE');room.reload();},'Session cancelled; members notified.');}}><Trash2 size={17}/></button></div>}</article>)}
    </section><section className="detail-section"><div className="section-heading"><h2>Recordings</h2>{owner&&<button className="secondary-button" onClick={()=>setRecordingForm(!recordingForm)}><Plus size={16}/>Add recording</button>}</div>{owner&&recordingForm&&<form className="editor-form" onSubmit={e=>{e.preventDefault();const body=formValues(e.currentTarget);void action.run(async()=>{await mutate(`/groups/${id}/recordings`,body);room.reload();setRecordingForm(false);},'Recording added.');}}><Field label="Recording title"><input name="title" required maxLength={160}/></Field><Field label="Shared recording URL"><input name="url" type="url" required placeholder="https://..."/></Field><Submit busy={action.busy}>Add recording</Submit></form>}{!room.data.recordings.length&&<Empty>No recordings yet.</Empty>}{room.data.recordings.map(r=><div className="detail-row" key={r.id}><External href={r.url}><Video size={18}/>{r.title}</External>{owner&&<button className="icon-button" title="Remove recording" disabled={action.busy} onClick={()=>{if(window.confirm('Remove this recording link?'))void action.run(async()=>{await mutate(`/groups/${id}/recordings/${r.id}`,undefined,'DELETE');room.reload();},'Recording removed.');}}><Trash2 size={17}/></button>}</div>)}</section></div><div><GroupModeration id={id!} owner={owner}/><GroupChat id={id!}/></div></div>}
  </CommunityPage>;
}
