import { Link } from 'react-router-dom';
import { ActionStatus,Empty,ErrorBox,Field,Submit,useAction } from './CommunityUI';
import { dateTime,formValues,mutate,useResource } from '../lib/community';
import { getCurrentUser } from '../lib/auth';
type Data={members:{id:string;name:string}[];removed:{id:string;name:string}[];announcements:{id:string;body:string;createdAt:string}[]};
export default function GroupModeration({id,owner}:{id:string;owner:boolean}){
 const result=useResource<Data>('/groups/'+id+'/moderation',15000),action=useAction(),user=getCurrentUser();
 return <section className="detail-section"><h2>Announcements</h2><ErrorBox error={result.error}/>{owner&&<form className="editor-form" onSubmit={e=>{e.preventDefault();const form=e.currentTarget,body=formValues(form);void action.run(async()=>{await mutate('/groups/'+id+'/announcements',body);form.reset();result.reload();},'Announcement posted; members notified.');}}><Field label="Announcement"><textarea name="body" required minLength={3} maxLength={2000}/></Field><Submit busy={action.busy}>Post announcement</Submit></form>}{result.data?.announcements.map(a=><article key={a.id} className="detail-row"><div><p className="preserve-lines">{a.body}</p><time className="muted">{dateTime(a.createdAt)}</time></div></article>)}{result.data&&!result.data.announcements.length&&<Empty>No announcements yet.</Empty>}<h2>Members</h2>{result.data?.members.map(m=><div key={m.id} className="detail-row"><strong>{m.name}</strong><div className="flex flex-wrap gap-3">{m.id!==user?.id&&<Link className="text-link" to={'/report?subject='+encodeURIComponent('Group member: '+m.name)+'&context='+encodeURIComponent('Group: '+id+'\nMember: '+m.id+'\n')}>Report</Link>}{owner&&m.id!==user?.id&&<button className="secondary-button" disabled={action.busy} onClick={()=>{if(confirm('Remove this member and block rejoining this group?'))void action.run(async()=>{await mutate('/groups/'+id+'/members/'+m.id,undefined,'DELETE');result.reload();},'Member removed.');}}>Remove</button>}</div></div>)}{owner&&!!result.data?.removed.length&&<><h3>Removed members</h3>{result.data.removed.map(m=><div className="detail-row" key={m.id}><span>{m.name}</span><button className="secondary-button" disabled={action.busy} onClick={()=>void action.run(async()=>{await mutate('/groups/'+id+'/bans/'+m.id,undefined,'DELETE');result.reload();},'This member can join the group again.')}>Allow rejoining</button></div>)}</>}<ActionStatus action={action}/></section>;
}
